// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrqgrcd8MkZknorhQJ-Ref49Y7pHMvSk4',
    appId: '1:692056231992:web:e7b2f1784648ea328596cd',
    messagingSenderId: '692056231992',
    projectId: 'to-do-app-40ba1',
    authDomain: 'to-do-app-40ba1.firebaseapp.com',
    storageBucket: 'to-do-app-40ba1.appspot.com',
    measurementId: 'G-F274FH81SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf9a_98IkjRcI87uZtgbwA5lp3mn7el6Q',
    appId: '1:692056231992:android:bec0009a160432178596cd',
    messagingSenderId: '692056231992',
    projectId: 'to-do-app-40ba1',
    storageBucket: 'to-do-app-40ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JfFhNhfzBHVP8cnLhyrzHs23Kqw8sgE',
    appId: '1:692056231992:ios:419c8e7a6399bc9a8596cd',
    messagingSenderId: '692056231992',
    projectId: 'to-do-app-40ba1',
    storageBucket: 'to-do-app-40ba1.appspot.com',
    iosClientId: '692056231992-b07uku55d381mtmtkjeeh2cu7kgf7f3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JfFhNhfzBHVP8cnLhyrzHs23Kqw8sgE',
    appId: '1:692056231992:ios:419c8e7a6399bc9a8596cd',
    messagingSenderId: '692056231992',
    projectId: 'to-do-app-40ba1',
    storageBucket: 'to-do-app-40ba1.appspot.com',
    iosClientId: '692056231992-b07uku55d381mtmtkjeeh2cu7kgf7f3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
